# .rubocop.yml
AllCops:
  TargetRubyVersion: '3.3.0'
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "config/puma.rb"
    - "config/spring.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"
    - "tmp/*"
    - "docker-build"
    - "db/seeds.rb"
    - "db/migrate/*"
    - "app/**/*"

Style/Documentation:
  Enabled: true
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Enabled: false