# .rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: "3.3.0"
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "config/puma.rb"
    - "config/spring.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"
    - "tmp/*"
    - "vendor/**/*"
    - "docker-build"
    - "db/seeds.rb"
    - "db/migrate/*"
    - "app/controllers/**/*"
    - "app/javascript/**/*"
    - "app/models/**/*"
    - "app/views/**/*"

Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/ExampleLength:
  Max: 30
RSpec/SubjectStub:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
