version: "3"
services:
  web:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail localhost:3000/up || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15.4-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blackboard_docker
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d blackboard_docker"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  cache:
    image: redis:7.2.6-alpine
    restart: always
    healthcheck:
      test: [
        "CMD-SHELL",
        "redis-cli", "--raw", "incr", "ping"
      ]
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
