default: &default
  external_video_hosting: false
  sidekiq_auth_enabled: false
  enable_chatwoot: false
  content_studio: false
  classroom_kit_enabled: false
  microlesson_enabled: false

production:
  <<: *default
  external_video_hosting: true
  sidekiq_auth_enabled: true
  enable_chatwoot: true
  content_studio: true

staging:
  <<: *default
  external_video_hosting: true
  sidekiq_auth_enabled: true
  enable_chatwoot: true
  content_studio: true
  classroom_kit_enabled: true

development:
  <<: *default
  content_studio: true
  classroom_kit_enabled: true

test:
  <<: *default

docker:
  <<: *default
