default: &default
  external_video_hosting: false
  sidekiq_auth_enabled: false
  enable_chatwoot: false

production:
  <<: *default
  external_video_hosting: true
  sidekiq_auth_enabled: true
  enable_chatwoot: true

staging:
  <<: *default
  external_video_hosting: true
  sidekiq_auth_enabled: true
  enable_chatwoot: true

development:
  <<: *default
  neo_ai_get_course_url: "http://127.0.0.1:8000/api/v1/course"
  neo_ai_token_url: "http://127.0.0.1:8000/api/v1/token"

test:
  <<: *default

docker:
  <<: *default
